### ISSUE TITLE
crash in ConfigBottomSheet

### ISSUE THREAD

**Issue by Irineu333** [Irineu333/DatabaseRules#8]
Fatal Exception: java.lang.IllegalStateException: Fragment ConfigBottomSheet{73fbb9c} (63521715-2b91-49e6-83eb-e313d869367f) not attached to a context.
       at androidx.fragment.app.Fragment.requireContext(Fragment.java:919)
       at androidx.fragment.app.Fragment.getResources(Fragment.java:983)
       at androidx.fragment.app.Fragment.getString(Fragment.java:1005)
       at com.neo.fbrules.main.presenter.fragment.bottomSheet.ConfigBottomSheet$setupViews$2.onDataChange(ConfigBottomSheet.kt:147)
       at com.google.firebase.database.Query$1.onDataChange(Query.java:191)
       at com.google.firebase.database.core.ValueEventRegistration.fireEvent(ValueEventRegistration.java:75)
       at com.google.firebase.database.core.view.DataEvent.fire(DataEvent.java:63)
       at com.google.firebase.database.core.view.EventRaiser$1.run(EventRaiser.java:55)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8587)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

6 events, 6 users

**Comment by Irineu333** [comment]
Deprecated.
